#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : multidict
Version  : 4.7.6
Release  : 24
URL      : https://files.pythonhosted.org/packages/65/d4/fabdcc5ee4451c8a8e177e27ddfd131a53a82ecc5a3b68468b7e9f8d70b4/multidict-4.7.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/65/d4/fabdcc5ee4451c8a8e177e27ddfd131a53a82ecc5a3b68468b7e9f8d70b4/multidict-4.7.6.tar.gz
Summary  : multidict implementation
Group    : Development/Tools
License  : Apache-2.0
Requires: multidict-license = %{version}-%{release}
Requires: multidict-python = %{version}-%{release}
Requires: multidict-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
multidict
        =========

%package license
Summary: license components for the multidict package.
Group: Default

%description license
license components for the multidict package.


%package python
Summary: python components for the multidict package.
Group: Default
Requires: multidict-python3 = %{version}-%{release}

%description python
python components for the multidict package.


%package python3
Summary: python3 components for the multidict package.
Group: Default
Requires: python3-core
Provides: pypi(multidict)

%description python3
python3 components for the multidict package.


%prep
%setup -q -n multidict-4.7.6
cd %{_builddir}/multidict-4.7.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589498415
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/multidict
cp %{_builddir}/multidict-4.7.6/LICENSE %{buildroot}/usr/share/package-licenses/multidict/9bda5c883efd96d295207e8ca8a4f38320fc2cf7
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/multidict/9bda5c883efd96d295207e8ca8a4f38320fc2cf7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
